/**
 * Generated by orval v7.12.2 🍺
 * Do not edit manually.
 * DevJobs API
 * API for the DevJobs platform
 * OpenAPI spec version: 1.0.0
 */
import * as axios from 'axios';
import type {
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import type {
  Company,
  CreateCompany,
  CreateJob,
  CreateUser,
  Job,
  User
} from './model';

/**
 * @summary List all users
 */
export const getUsers = <TData = AxiosResponse<User[]>>(
     options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.get(
      `/users`,options
    );
  }

/**
 * @summary Register a new user
 */
export const postUsers = <TData = AxiosResponse<User>>(
    createUser: CreateUser, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.post(
      `/users`,
      createUser,options
    );
  }

/**
 * @summary List all companies
 */
export const getCompanies = <TData = AxiosResponse<Company[]>>(
     options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.get(
      `/companies`,options
    );
  }

/**
 * @summary Create a new company
 */
export const postCompanies = <TData = AxiosResponse<Company>>(
    createCompany: CreateCompany, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.post(
      `/companies`,
      createCompany,options
    );
  }

/**
 * @summary List all jobs
 */
export const getJobs = <TData = AxiosResponse<Job[]>>(
     options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.get(
      `/jobs`,options
    );
  }

/**
 * @summary Create a new job posting
 */
export const postJobs = <TData = AxiosResponse<Job>>(
    createJob: CreateJob, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.post(
      `/jobs`,
      createJob,options
    );
  }

export type GetUsersResult = AxiosResponse<User[]>
export type PostUsersResult = AxiosResponse<User>
export type GetCompaniesResult = AxiosResponse<Company[]>
export type PostCompaniesResult = AxiosResponse<Company>
export type GetJobsResult = AxiosResponse<Job[]>
export type PostJobsResult = AxiosResponse<Job>
