/**
 * Generated by orval v7.12.2 🍺
 * Do not edit manually.
 * DevJobs API
 * API for the DevJobs platform
 * OpenAPI spec version: 1.0.0
 */
import * as axios from 'axios';
import type {
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import type {
  BaseCompany,
  CompanyResponse,
  CreateJob,
  JobResponse,
  UserResponse
} from './model';

/**
 * @summary List all users
 */
export const getUsers = <TData = AxiosResponse<UserResponse[]>>(
     options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.get(
      `/users`,options
    );
  }

/**
 * @summary Register a new user
 */
export const postUsers = <TData = AxiosResponse<UserResponse>>(
    postUsersBody: unknown, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.post(
      `/users`,
      postUsersBody,options
    );
  }

/**
 * @summary List all companies
 */
export const getCompanies = <TData = AxiosResponse<CompanyResponse[]>>(
     options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.get(
      `/companies`,options
    );
  }

/**
 * @summary Create a new company
 */
export const postCompanies = <TData = AxiosResponse<CompanyResponse>>(
    baseCompany: BaseCompany, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.post(
      `/companies`,
      baseCompany,options
    );
  }

/**
 * @summary List all jobs
 */
export const getJobs = <TData = AxiosResponse<JobResponse[]>>(
     options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.get(
      `/jobs`,options
    );
  }

/**
 * @summary Create a new job posting
 */
export const postJobs = <TData = AxiosResponse<JobResponse>>(
    createJob: CreateJob, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.post(
      `/jobs`,
      createJob,options
    );
  }

export type GetUsersResult = AxiosResponse<UserResponse[]>
export type PostUsersResult = AxiosResponse<UserResponse>
export type GetCompaniesResult = AxiosResponse<CompanyResponse[]>
export type PostCompaniesResult = AxiosResponse<CompanyResponse>
export type GetJobsResult = AxiosResponse<JobResponse[]>
export type PostJobsResult = AxiosResponse<JobResponse>
