/**
 * Generated by orval v7.12.2 🍺
 * Do not edit manually.
 * DevJobs API
 * API for the DevJobs platform
 * OpenAPI spec version: 1.0.0
 */

export interface BaseJob {
  title: string;
  /** Reference to the company that created this job */
  companyId: string;
  location: string;
  description?: string;
}
