/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * DevJobs API
 * API for the DevJobs platform
 * OpenAPI spec version: 1.0.0
 */
import type { BaseCompany } from './baseCompany';
import type { CompanyResponseAllOf } from './companyResponseAllOf';

export type CompanyResponse = BaseCompany & CompanyResponseAllOf;
