/**
 * Generated by orval v7.12.2 🍺
 * Do not edit manually.
 * DevJobs API
 * API for the DevJobs platform
 * OpenAPI spec version: 1.0.0
 */

export type CreateUserRole = typeof CreateUserRole[keyof typeof CreateUserRole];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CreateUserRole = {
  jobSeeker: 'jobSeeker',
  companyUser: 'companyUser',
} as const;
