/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * DevJobs API
 * API for the DevJobs platform
 * OpenAPI spec version: 1.0.0
 */
import type { BaseUser } from './baseUser';
import type { CreateUserAllOf } from './createUserAllOf';

export type CreateUser = BaseUser & CreateUserAllOf;
