/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * DevJobs API
 * API for the DevJobs platform
 * OpenAPI spec version: 1.0.0
 */
import type { BaseJob } from './baseJob';
import type { CreateJobAllOf } from './createJobAllOf';

export type CreateJob = BaseJob & CreateJobAllOf;
