/**
 * Generated by orval v7.12.2 🍺
 * Do not edit manually.
 * DevJobs API
 * API for the DevJobs platform
 * OpenAPI spec version: 1.0.0
 */
import type { CreateUserRole } from './createUserRole';

export interface CreateUser {
  name: string;
  email: string;
  password: string;
  role: CreateUserRole;
  /** Required if role is companyUser */
  companyId?: string;
}
