/**
 * Generated by orval v7.12.2 🍺
 * Do not edit manually.
 * DevJobs API
 * API for the DevJobs platform
 * OpenAPI spec version: 1.0.0
 */
import type { BaseJob } from './baseJob';
import type { JobResponseAllOf } from './jobResponseAllOf';

export type JobResponse = BaseJob & JobResponseAllOf;
